<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'dunphp\\base\\databasecontroller' => '/Base/DatabaseController.php',
                'dunphp\\base\\resourcecontroller' => '/Base/ResourceController.php',
                'dunphp\\base\\viewcontroller' => '/Base/ViewController.php',
                'dunphp\\classes\\controller\\iactioncontroller' => '/Classes/Controller/IActionController.php',
                'dunphp\\classes\\controller\\standardcontroller' => '/Classes/Controller/StandardController.php',
                'dunphp\\classes\\repository\\genericrepository' => '/Classes/Repository/GenericRepository.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
